### ISSUE TITLE
Does not build due to miscapitalization of header file.

### ISSUE THREAD

**Issue by Brunste** [cypresssemiconductorco/mtb-example-psoc6-capsense-buttons-slider-freertos#1]
This demo does not build with `make program` due to line 52 in main.c which mistypes `#include "FreeRTOS.h` as `#include "freeRTOS.h"`

Changing the line to `#include "FreeRTOS.h"` resolves the issue.

**Comment by rmbk19** [comment]
Hi @Brunste, 

Thank you for pointing this out. As ModusToolbox 2.0 is an Eclipse based IDE, it assumes the case sensitivity defined by the local OS. In other words, if your OS allows case sensitive naming of files and folders then even MTB 2.0 will be case sensitive. 
I tried building the project as it is and I was able to build the project successfully. Can you please let me know the OS that you are using? If you are using Windows, then the  Windows 10 April 2018 Update (version 1803) allows you to enable/disable case sensitive naming. Please refer to this link - [Enable/Disable case sensitive naming](https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10).

Hope this helps,

Thanks and Regards,
Rakshith M B

**Comment by Brunste** [comment]
Greetings.

I am using Arch Linux and using make to build the project. As I said, correcting the capitalization of the header file resolved my issue, but those building on GNU/Linux based operating systems will likely run into the same issue due to case sensitivity. If other operating systems are able to handle it either way, I would suggest capitalizing it to match the file name for better compatibility. That is obviously up to you though.

Thank you for your response and assistance.

**Comment by rmbk19** [comment]
Hi @Brunste,

You are right. Thank you for pointing this out. The issue will be fixed internally and an update will be pushed to GitHub repo.

Regards,
Rakshith M B

**Comment by arvi-kris-cy** [comment]
This is fixed with the [v1.1.0 release](https://github.com/cypresssemiconductorco/mtb-example-psoc6-capsense-buttons-slider-freertos/tree/release-v1.1.0)
